map H g^
map L g$
map Y g0
inoremap JJ <Esc>
vmap JJ <Esc> 
inoremap ( ()<LEFT>
inoremap [ []<LEFT>
inoremap { {}<LEFT>
inoremap ' ''<LEFT>
inoremap " ""<LEFT>
inoremap （ （）<LEFT>
inoremap 《 《》<LEFT>
inoremap $ $$<LEFT>
map <C-l> <C-w>l
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
noremap - :-tabnext<CR>
noremap = :+tabnext<CR>
noremap s <nop>
noremap j gj
noremap k gk
noremap <C-H> H
noremap <C-M> M
noremap <C-L> L
noremap M :nohlsearch<CR>
